### ISSUE TITLE
Error when using Spring Boot recommendations to create deployable war file

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-core#155]
- create new Jmix project (1.0.0-snapshot, JDK 11)
- use these instructions to configure deployable WAR:

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file

sample project attached
[jwar.zip](https://github.com/Haulmont/jmix-core/files/6440266/jwar.zip)

Try to run "bootWar" task - it fails with exception:
```
Execution failed for task ':bootWarMainClassName'.
> Could not resolve all files for configuration ':providedRuntime'.
   > Could not find org.springframework.boot:spring-boot-starter-tomcat:.
     Required by:
         project :
```

The build can't resolve `providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'` dependency.

**Comment by alexbudarov** [comment]
Note that if you omit this declaration, then WAR is built successfully.
However with excessive Tomcat embeded libraries.
I suspect that these excessive libraries cause another problem in runtime, not yet posted as a bug:
```
Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://localhost/jwar
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:325)
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:272)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
        ... 60 more
Caused by: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
        ... 67 more
```
see https://forum.jmix.io/t/deployable-war-to-tomcat/69

**Comment by andreysubbotin** [comment]
It's a common spring boot problem.
https://stackoverflow.com/questions/51018489/failed-to-get-driver-instance-for-oracle-and-hikaricp
https://www.bswen.com/2019/11/springboot-How-to-deploy-springboot-applications-to-tomcat.html

Add this line to your application.properties:
```spring.datasource.driver-class-name=org.postgresql.Driver```

**Comment by andreysubbotin** [comment]
Jmix Studio issues: https://youtrack.haulmont.com/issue/JST-1303, https://youtrack.haulmont.com/issue/JST-1300

**Comment by andreysubbotin** [comment]
For QA: 
-  create new Jmix project (1.0.0-snapshot, JDK 11)
-  use these instructions to configure deployable WAR:
 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file
   -  Extend your application’s main class from SpringBootServletInitializer
     ``` 
     @SpringBootApplication 
     public class MyApplication extends SpringBootServletInitializer {

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(MyApplication.class);
    }
    ```
   - Apply war plugin in the `build.gradle`
    ```
    apply plugin: 'war'
    ``` 
   -

**Comment by maistrenkoIulia** [comment]
verified
