### ISSUE TITLE
Error deploying application to Google Cloud Platform 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-core#217]
based on [forum's question](https://forum.jmix.io/t/gcp-app-engine-deploy-on-version-1-0-0-issue/363)

**Environment:**
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.1-212
IntelliJ version: IntelliJ IDEA 2021.2 (Community Edition)

**TC:**
1. Create Google Cloud Platform project using [docs](https://docs.jmix.io/jmix/deployment/deploy-to-google-cloud.html)
2. Open attached Jmix project and set your properties in application-gae.properties
3. Run app by console command `./gradlew appengineDeploy`

**AR:**
Build failed:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/ae5780b6-8a6d-4c4e-a3e3-50acf44b20d5)

Full log:
```
starting build "67ae8f30-bc1e-4ff4-91a3-d5618c2fb958"

FETCHSOURCE
BUILD
Starting Step #0 - "fetcher"
Step #0 - "fetcher": Already have image (with digest): gcr.io/cloud-builders/gcs-fetcher
Step #0 - "fetcher": Fetching manifest gs://staging.jmixproject2021.appspot.com/ae/fd21be9a-335d-44be-b5bd-0165848008e6/manifest.json.
Step #0 - "fetcher": Processing 2 files.
Step #0 - "fetcher": ******************************************************
Step #0 - "fetcher": Status:                      SUCCESS
Step #0 - "fetcher": Started:                     2021-08-05T13:50:16Z
Step #0 - "fetcher": Completed:                   2021-08-05T13:50:16Z
Step #0 - "fetcher": Requested workers:    200
Step #0 - "fetcher": Actual workers:         2
Step #0 - "fetcher": Total files:            2
Step #0 - "fetcher": Total retries:          0
Step #0 - "fetcher": GCS timeouts:           0
Step #0 - "fetcher": MiB downloaded:         0.02 MiB
Step #0 - "fetcher": MiB/s throughput:       0.09 MiB/s
Step #0 - "fetcher": Time for manifest:    389.46 ms
Step #0 - "fetcher": Total time:             0.65 s
Step #0 - "fetcher": ******************************************************
Finished Step #0 - "fetcher"
Starting Step #1 - "prep"
Step #1 - "prep": Already have image (with digest): gcr.io/cloud-builders/gcloud
Finished Step #1 - "prep"
Starting Step #2 - "pre-tag"
Step #2 - "pre-tag": Pulling image: gcr.io/gae-runtimes/crane:shell
Step #2 - "pre-tag": shell: Pulling from gae-runtimes/crane
Step #2 - "pre-tag": 4000adbbc3eb: Pulling fs layer
Step #2 - "pre-tag": 69e2f037cdb3: Pulling fs layer
Step #2 - "pre-tag": e43810d8344f: Pulling fs layer
Step #2 - "pre-tag": 72164b581b02: Pulling fs layer
Step #2 - "pre-tag": 8250a9b721ab: Pulling fs layer
Step #2 - "pre-tag": 72164b581b02: Waiting
Step #2 - "pre-tag": 8250a9b721ab: Waiting
Step #2 - "pre-tag": 4000adbbc3eb: Verifying Checksum
Step #2 - "pre-tag": 4000adbbc3eb: Download complete
Step #2 - "pre-tag": 72164b581b02: Verifying Checksum
Step #2 - "pre-tag": 72164b581b02: Download complete
Step #2 - "pre-tag": 69e2f037cdb3: Verifying Checksum
Step #2 - "pre-tag": 69e2f037cdb3: Download complete
Step #2 - "pre-tag": e43810d8344f: Verifying Checksum
Step #2 - "pre-tag": e43810d8344f: Download complete
Step #2 - "pre-tag": 4000adbbc3eb: Pull complete
Step #2 - "pre-tag": 8250a9b721ab: Verifying Checksum
Step #2 - "pre-tag": 8250a9b721ab: Download complete
Step #2 - "pre-tag": 69e2f037cdb3: Pull complete
Step #2 - "pre-tag": e43810d8344f: Pull complete
Step #2 - "pre-tag": 72164b581b02: Pull complete
Step #2 - "pre-tag": 8250a9b721ab: Pull complete
Step #2 - "pre-tag": Digest: sha256:70d1c3be3db90db0bc52538557e7232bb5c4fdc16cdadf82e49739e633f6ec4e
Step #2 - "pre-tag": Status: Downloaded newer image for gcr.io/gae-runtimes/crane:shell
Step #2 - "pre-tag": gcr.io/gae-runtimes/crane:shell
Step #2 - "pre-tag": 2021/08/05 13:50:21 Copying from eu.gcr.io/jmixproject2021/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:latest to eu.gcr.io/jmixproject2021/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:67ae8f30-bc1e-4ff4-91a3-d5618c2fb958
Step #2 - "pre-tag": 2021/08/05 13:50:21 fetching "eu.gcr.io/jmixproject2021/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:latest": GET https://eu.gcr.io/v2/jmixproject2021/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/jmixproject2021/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache/manifests/latest".
Step #2 - "pre-tag": Unable to tag previous cache image. This is expected for new or infrequent deployments.
Step #2 - "pre-tag": 2021/08/05 13:50:21 Copying from eu.gcr.io/jmixproject2021/app-engine-tmp/app/ttl-2h/default/buildpack-app:latest to eu.gcr.io/jmixproject2021/app-engine-tmp/app/ttl-2h:fd21be9a-335d-44be-b5bd-0165848008e6
Step #2 - "pre-tag": 2021/08/05 13:50:21 fetching "eu.gcr.io/jmixproject2021/app-engine-tmp/app/ttl-2h/default/buildpack-app:latest": GET https://eu.gcr.io/v2/jmixproject2021/app-engine-tmp/app/ttl-2h/default/buildpack-app/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/jmixproject2021/app-engine-tmp/app/ttl-2h/default/buildpack-app/manifests/latest".
Step #2 - "pre-tag": Unable to tag previous application image. This is expected for new or infrequent deployments.
Finished Step #2 - "pre-tag"
Starting Step #3 - "detector"
Step #3 - "detector": Pulling image: eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #3 - "detector": java11_20210713a_11_0_RC00: Pulling from gae-runtimes/buildpacks/java11/builder
Step #3 - "detector": 228505c46125: Already exists
Step #3 - "detector": 52b243a9211b: Already exists
Step #3 - "detector": 3c2cba919283: Already exists
Step #3 - "detector": 94b9159bf001: Already exists
Step #3 - "detector": de3a1d1384e7: Already exists
Step #3 - "detector": f48f5e846525: Already exists
Step #3 - "detector": 56ae46af1768: Already exists
Step #3 - "detector": 2fd01a3d81c6: Already exists
Step #3 - "detector": 47e8f083a103: Already exists
Step #3 - "detector": f5e5bd2ed230: Already exists
Step #3 - "detector": b1b336c451b8: Already exists
Step #3 - "detector": 7ea613dfdd99: Pulling fs layer
Step #3 - "detector": d766fd231f08: Pulling fs layer
Step #3 - "detector": b420e9935e5a: Pulling fs layer
Step #3 - "detector": 5db230bdc0b7: Pulling fs layer
Step #3 - "detector": 45ac3b451b35: Pulling fs layer
Step #3 - "detector": 6c65d250ee15: Pulling fs layer
Step #3 - "detector": 4be18f414ba2: Pulling fs layer
Step #3 - "detector": 25032b00367d: Pulling fs layer
Step #3 - "detector": ba44dec8db35: Pulling fs layer
Step #3 - "detector": ca1c79bb8ba7: Pulling fs layer
Step #3 - "detector": 06f428a8446f: Pulling fs layer
Step #3 - "detector": df2a11ebcd38: Pulling fs layer
Step #3 - "detector": 285132f03d7a: Pulling fs layer
Step #3 - "detector": 9766816392e1: Pulling fs layer
Step #3 - "detector": 59ac841a891c: Pulling fs layer
Step #3 - "detector": 867b0db87570: Pulling fs layer
Step #3 - "detector": 7e8f029fa81d: Pulling fs layer
Step #3 - "detector": 49d4cb819a29: Pulling fs layer
Step #3 - "detector": ca0c80a2f745: Pulling fs layer
Step #3 - "detector": 4f4fb700ef54: Pulling fs layer
Step #3 - "detector": 5db230bdc0b7: Waiting
Step #3 - "detector": 45ac3b451b35: Waiting
Step #3 - "detector": 6c65d250ee15: Waiting
Step #3 - "detector": 4be18f414ba2: Waiting
Step #3 - "detector": 25032b00367d: Waiting
Step #3 - "detector": ba44dec8db35: Waiting
Step #3 - "detector": ca1c79bb8ba7: Waiting
Step #3 - "detector": 06f428a8446f: Waiting
Step #3 - "detector": df2a11ebcd38: Waiting
Step #3 - "detector": 285132f03d7a: Waiting
Step #3 - "detector": 9766816392e1: Waiting
Step #3 - "detector": 59ac841a891c: Waiting
Step #3 - "detector": 7e8f029fa81d: Waiting
Step #3 - "detector": 49d4cb819a29: Waiting
Step #3 - "detector": ca0c80a2f745: Waiting
Step #3 - "detector": 4f4fb700ef54: Waiting
Step #3 - "detector": 867b0db87570: Waiting
Step #3 - "detector": b420e9935e5a: Verifying Checksum
Step #3 - "detector": b420e9935e5a: Download complete
Step #3 - "detector": 5db230bdc0b7: Verifying Checksum
Step #3 - "detector": 5db230bdc0b7: Download complete
Step #3 - "detector": 45ac3b451b35: Verifying Checksum
Step #3 - "detector": 45ac3b451b35: Download complete
Step #3 - "detector": 6c65d250ee15: Verifying Checksum
Step #3 - "detector": 6c65d250ee15: Download complete
Step #3 - "detector": 4be18f414ba2: Verifying Checksum
Step #3 - "detector": 4be18f414ba2: Download complete
Step #3 - "detector": 25032b00367d: Verifying Checksum
Step #3 - "detector": 25032b00367d: Download complete
Step #3 - "detector": ba44dec8db35: Verifying Checksum
Step #3 - "detector": ba44dec8db35: Download complete
Step #3 - "detector": ca1c79bb8ba7: Verifying Checksum
Step #3 - "detector": ca1c79bb8ba7: Download complete
Step #3 - "detector": 06f428a8446f: Verifying Checksum
Step #3 - "detector": 06f428a8446f: Download complete
Step #3 - "detector": df2a11ebcd38: Verifying Checksum
Step #3 - "detector": df2a11ebcd38: Download complete
Step #3 - "detector": 285132f03d7a: Verifying Checksum
Step #3 - "detector": 285132f03d7a: Download complete
Step #3 - "detector": 9766816392e1: Verifying Checksum
Step #3 - "detector": 9766816392e1: Download complete
Step #3 - "detector": d766fd231f08: Verifying Checksum
Step #3 - "detector": d766fd231f08: Download complete
Step #3 - "detector": 59ac841a891c: Verifying Checksum
Step #3 - "detector": 59ac841a891c: Download complete
Step #3 - "detector": 867b0db87570: Verifying Checksum
Step #3 - "detector": 867b0db87570: Download complete
Step #3 - "detector": 7ea613dfdd99: Verifying Checksum
Step #3 - "detector": 7ea613dfdd99: Download complete
Step #3 - "detector": 49d4cb819a29: Verifying Checksum
Step #3 - "detector": 49d4cb819a29: Download complete
Step #3 - "detector": ca0c80a2f745: Verifying Checksum
Step #3 - "detector": ca0c80a2f745: Download complete
Step #3 - "detector": 4f4fb700ef54: Verifying Checksum
Step #3 - "detector": 4f4fb700ef54: Download complete
Step #3 - "detector": 7e8f029fa81d: Verifying Checksum
Step #3 - "detector": 7e8f029fa81d: Download complete
Step #3 - "detector": 7ea613dfdd99: Pull complete
Step #3 - "detector": d766fd231f08: Pull complete
Step #3 - "detector": b420e9935e5a: Pull complete
Step #3 - "detector": 5db230bdc0b7: Pull complete
Step #3 - "detector": 45ac3b451b35: Pull complete
Step #3 - "detector": 6c65d250ee15: Pull complete
Step #3 - "detector": 4be18f414ba2: Pull complete
Step #3 - "detector": 25032b00367d: Pull complete
Step #3 - "detector": ba44dec8db35: Pull complete
Step #3 - "detector": ca1c79bb8ba7: Pull complete
Step #3 - "detector": 06f428a8446f: Pull complete
Step #3 - "detector": df2a11ebcd38: Pull complete
Step #3 - "detector": 285132f03d7a: Pull complete
Step #3 - "detector": 9766816392e1: Pull complete
Step #3 - "detector": 59ac841a891c: Pull complete
Step #3 - "detector": 867b0db87570: Pull complete
Step #3 - "detector": 7e8f029fa81d: Pull complete
Step #3 - "detector": 49d4cb819a29: Pull complete
Step #3 - "detector": ca0c80a2f745: Pull complete
Step #3 - "detector": 4f4fb700ef54: Pull complete
Step #3 - "detector": Digest: sha256:42a2b12d3b6a7e93c9b380ae886ca1044bb7cf1112f9250ccdc83af2d49edabc
Step #3 - "detector": Status: Downloaded newer image for eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #3 - "detector": eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #3 - "detector": ======== Output: google.java.maven@0.9.0 ========
Step #3 - "detector": Opting out: none of the following found: pom.xml or .mvn/extensions.xml.
Step #3 - "detector": ======== Output: google.java.appengine@0.9.0 ========
Step #3 - "detector": Opting in: always enabled
Step #3 - "detector": ======== Output: google.java.clear_source@0.9.0 ========
Step #3 - "detector": Opting out: GOOGLE_CLEAR_SOURCE not set
Step #3 - "detector": ======== Output: google.utils.label@0.0.1 ========
Step #3 - "detector": Opting in: always enabled
Step #3 - "detector": ======== Results ========
Step #3 - "detector": fail: google.java.maven@0.9.0
Step #3 - "detector": pass: google.java.appengine@0.9.0
Step #3 - "detector": skip: google.java.clear_source@0.9.0
Step #3 - "detector": pass: google.utils.label@0.0.1
Step #3 - "detector": ======== Output: google.java.gradle@0.9.0 ========
Step #3 - "detector": Opting out: neither build.gradle nor build.gradle.kts found
Step #3 - "detector": ======== Output: google.java.appengine@0.9.0 ========
Step #3 - "detector": Opting in: always enabled
Step #3 - "detector": ======== Output: google.java.clear_source@0.9.0 ========
Step #3 - "detector": Opting out: GOOGLE_CLEAR_SOURCE not set
Step #3 - "detector": ======== Output: google.utils.label@0.0.1 ========
Step #3 - "detector": Opting in: always enabled
Step #3 - "detector": ======== Results ========
Step #3 - "detector": skip: google.java.gradle@0.9.0
Step #3 - "detector": pass: google.java.appengine@0.9.0
Step #3 - "detector": skip: google.java.clear_source@0.9.0
Step #3 - "detector": pass: google.utils.label@0.0.1
Step #3 - "detector": Resolving plan... (try #1)
Step #3 - "detector": 2 of 4 buildpacks participating
Step #3 - "detector": google.java.appengine 0.9.0
Step #3 - "detector": google.utils.label    0.0.1
Finished Step #3 - "detector"
Starting Step #4 - "analyzer"
Step #4 - "analyzer": Already have image (with digest): eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #4 - "analyzer": Previous image with name "eu.gcr.io/jmixproject2021/app-engine-tmp/app/ttl-2h:fd21be9a-335d-44be-b5bd-0165848008e6" not found
Step #4 - "analyzer": Layer cache not found
Finished Step #4 - "analyzer"
Starting Step #5 - "restorer"
Step #5 - "restorer": Already have image (with digest): eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #5 - "restorer": Layer cache not found
Finished Step #5 - "restorer"
Starting Step #6 - "builder"
Step #6 - "builder": Already have image (with digest): eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00
Step #6 - "builder": === Java - App Engine (google.java.appengine@0.9.0) ===
Step #6 - "builder": DEBUG: Using GOOGLE_RUNTIME: java11
Step #6 - "builder": Failure: (ID: 838926df) did not find any jar files with a Main-Class manifest entry
Step #6 - "builder": --------------------------------------------------------------------------------
Step #6 - "builder": Running "mv -f /builder/outputs/output-5577006791947779410 /builder/outputs/output"
Step #6 - "builder": Done "mv -f /builder/outputs/output-5577006791947779410 /builder/o..." (34.015963ms)
Step #6 - "builder": ERROR: failed to build: exit status 1
Finished Step #6 - "builder"
ERROR
ERROR: build step 6 "eu.gcr.io/gae-runtimes/buildpacks/java11/builder:java11_20210713a_11_0_RC00" failed: step exited with non-zero status: 145
```

[project](https://app.zenhub.com/files/285281777/0e00db92-a601-4c39-9c6e-109cc2f75ae2/download)

**Comment by plakhov** [comment]
Try to add into 'app.yaml' following line:
`entrypoint: java -jar gcloud.jar`
After that, I was able to deploy the attached project to GCloud

**Comment by owlet1997** [comment]
Error starting app in GCP:
```

java.sql.SQLException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@f270db8c[file =/workspace/.jmix/hsqldb/j.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /workspace/.jmix/hsqldb/j.lck (No such file or directory)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:272) ~[liquibase-core-4.3.5.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar!/:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.8.jar!/:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3.8.jar!/:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.8.jar!/:5.3.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.2.jar!/:2.5.2]
	at com.company.jmixpro.JmixProApplication.main(JmixProApplication.java:25) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[jmix-pro-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[jmix-pro-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[jmix-pro-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[jmix-pro-0.0.1-SNAPSHOT.jar:na]
Caused by: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@f270db8c[file =/workspace/.jmix/hsqldb/j.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: /workspace/.jmix/hsqldb/j.lck (No such file or directory)
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.persist.Logger.acquireLock(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.persist.Logger.open(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.Database.reopen(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.Database.open(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	at org.hsqldb.DatabaseManager.newSession(Unknown Source) ~[hsqldb-2.5.2.jar!/:2.5.2]
	... 39 common frames omitted
```

**Comment by andreysubbotin** [comment]
Use Postgres instead of HSQL. See https://docs.jmix.io/jmix/deployment/deploy-to-google-cloud.html

**Comment by owlet1997** [comment]
Needs to fix in [docs](https://docs.jmix.io/jmix/deployment/deploy-to-google-cloud.html):
- add code below to `appengine` Gradle task
``` stage {
        artifact = "${buildDir}/libs/${project.name}-${project.version}.jar"
}
```
- fix property in application-xxx.properties
`main.datasource.jdbcUrl` -> `main.datasource.url`
