### ISSUE TITLE
Remove serializable inheritance from entity model

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-core#28]
```
java.io.NotSerializableException: com.company.jmixts.entity.Task
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at java.base/java.util.ArrayList.writeObject(ArrayList.java:896)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at io.jmix.core.impl.StandardSerialization.serialize(StandardSerialization.java:42)
	at io.jmix.core.impl.StandardSerialization.serialize(StandardSerialization.java:89)
	at io.jmix.ui.model.impl.DataContextImpl.isolate(DataContextImpl.java:675)
	at io.jmix.ui.model.impl.DataContextImpl.commitToDataManager(DataContextImpl.java:650)
	at io.jmix.ui.model.impl.DataContextImpl.performCommit(DataContextImpl.java:642)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.jav
```

**Comment by andreysubbotin** [comment]
Fixed the problem in Haulmont/jmix-core#10
