### ISSUE TITLE
Validate data format strings on application start

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-core#88]
Often users modify data format strings in such a way that backoffice-ui components can't use them.

But developer gets a warning very late in the running application - only when the string is used by the component (e.g. by dateField).

Example project attached.
[moifr.zip](https://github.com/Haulmont/jmix-core/files/5975652/moifr.zip)

I modified:
```
dateTimeFormat=dd.MM.yyyy HH:mm:ss z
```

- Launch application
- The table in the user browser works OK with this format.
- But dateField in user editor - can't work with it and throws obscure exception:

```
Caused by: java.time.DateTimeException: Unable to extract value: class java.time.LocalTime
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:282) ~[na:1.8.0_282]
	at java.time.format.DateTimeFormatterBuilder$ZoneTextPrinterParser.format(DateTimeFormatterBuilder.java:3693) ~[na:1.8.0_282]
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2190) ~[na:1.8.0_282]
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746) ~[na:1.8.0_282]
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720) ~[na:1.8.0_282]
	at java.time.LocalTime.format(LocalTime.java:1413) ~[na:1.8.0_282]
	at io.jmix.ui.widget.JmixTimeField.formatValue(JmixTimeField.java:218) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixTimeField.doSetValue(JmixTimeField.java:99) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixTimeField.doSetValue(JmixTimeField.java:39) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:140) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
	at io.jmix.ui.widget.JmixTimeField.setValue(JmixTimeField.java:92) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixTimeField.setValue(JmixTimeField.java:39) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:53) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
	at io.jmix.ui.widget.JmixTimeFieldWrapper.setValueToPresentation(JmixTimeFieldWrapper.java:228) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixTimeFieldWrapper.doSetValue(JmixTimeFieldWrapper.java:151) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixTimeFieldWrapper.doSetValue(JmixTimeFieldWrapper.java:36) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:140) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:53) ~[vaadin-server-8.9.2-6-jmix.jar:8.9.2-6-jmix]
	at io.jmix.ui.component.impl.DateFieldImpl.setValueToPresentation(DateFieldImpl.java:403) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.DateFieldImpl.setValueToPresentation(DateFieldImpl.java:60) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractViewComponent.setValue(AbstractViewComponent.java:108) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.data.value.ValueBinder$ValueBindingImpl.valueSourceStateChanged(ValueBinder.java:269) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
```

So we have two problems:
- late feedback about wrong format strings
- obscure error message from the UI component

**Suggestion**
Validate data format strings on project start.
Validation rules should consider everything, should disallow to use symbols that can't be used by UI components.
If datatype format string is wrong, abort system start and print error message. Include into the message: locale, string key, string value.

If such formats as above are acceptable - then we should improve DateField to consume formats as presented above.

**Comment by alexbudarov** [comment]
Example forum topics with invalid strings:
- https://www.cuba-platform.com/discuss/t/timefield-datetimeparseexception-datatype-format-strings-bug/13943
```
timeFormat = hh:mm a
DateTimeParseException: Text ‘02:03 A’ could not be parsed at index 6
```
- https://www.cuba-platform.com/discuss/t/datetime-patterns/10168
```
dateTimeFormat = MM/dd/yyyy hh:mm aa
java.lang.IllegalArgumentException: Too many pattern letters: a
```

- https://www.cuba-platform.ru/discuss/t/oshibka-entity-inspector-dlya-sushhnosti-s-date/3797
```
dateTimeFormat=yyyy-MM-dd HH:mm, EE
```

**Comment by alexbudarov** [comment]
When we have logic for runtime validation, we will be able to include it to Studio also.
