### ISSUE TITLE
Exception on time attribute serialization

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-core#89]
Create entity with time attribute:
```
    public Time getTimeAttr() {
        return timeAttr;
    }

    public void setTimeAttr(Time timeAttr) {
        this.timeAttr = timeAttr;
    }
```

Try to fetch it via rest api:

```
java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: HourOfDay
	at java.base/java.time.LocalDate.get0(LocalDate.java:708) ~[na:na]
	at java.base/java.time.LocalDate.getLong(LocalDate.java:687) ~[na:na]
	at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308) ~[na:na]
	at java.base/java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2702) ~[na:na]
	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2341) ~[na:na]
	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2341) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1843) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817) ~[na:na]
	at java.base/java.time.LocalDate.format(LocalDate.java:1816) ~[na:na]
	at io.jmix.core.metamodel.datatype.impl.TimeDatatype.format(TimeDatatype.java:58) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.writeSimpleProperty(EntitySerializationImpl.java:368) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.writeFields(EntitySerializationImpl.java:340) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serializeEntity(EntitySerializationImpl.java:241) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serialize(EntitySerializationImpl.java:214) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serialize(EntitySerializationImpl.java:186) 
```

**Comment by owlet1997** [comment]
it was checked via using frontend module

TC:

1. Open [attached](https://github.com/Haulmont/jmix-core/files/6082444/access.zip) project
2. Run app
3. Open OffsetTime Management page
4. Create new instance -> Save it

AR:
there is an error
![image](https://user-images.githubusercontent.com/45730069/109945050-4e256180-7cf0-11eb-982e-13af45c59e3e.png)
and [exception](https://github.com/Haulmont/jmix-core/files/6082425/offsetexception.txt), instance has not been saved

5. Open Time Management page
6. Create new instance -> Save it

AR:
there is an error
![image](https://user-images.githubusercontent.com/45730069/109945158-672e1280-7cf0-11eb-94b0-34c32c79ad16.png)
and [exception](https://github.com/Haulmont/jmix-core/files/6082439/timeexception.txt), instance has not been saved

**Comment by web-devel** [comment]
@owlet1997 could you create a ticket in @haulmont/jmix-frontend

**Comment by owlet1997** [comment]
problem cause was using incorrect type java.sql.Time
